# basic config
baseURL = "https://jcleal.me/"
languageCode = "en-us"
title="Jordan Cleal"
theme = "hugo-ink"
paginate = 3

# https://xyproto.github.io/splash/docs/all.html
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    subtitle = "A DevOps Engineer focused on Go, Bash, & AWS."
    featherIconsCDN = true
    avatar = "https://jcleal.me/my-face.png"
    mode = "dark"
    customCSS = "css/custom.css"
    customDarkCSS = "css/custom.dark.css"

# navigation
[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "Work"
url = "/work"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5

[taxonomies]
   tag = "tags"