name: update
on:
  repository_dispatch:
    types: [update]

jobs:
  update:
    name: Update repository with changes from template
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update repository?
        run: |
          echo "##[group]Configuring GitHub user"
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          echo "##[endgroup]"

          echo "##[group]Checking for any files that have changed"
          ./bin/update-template.sh
          echo "##[endgroup]"

          echo "##[group]Pushing"
          git push origin HEAD:master
          echo "##[endgroup]"