name: update
on:
  repository_dispatch:
    types: [update]

jobs:
  update:
    name: Update repository with changes from template
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update repository?
        run: ./bin/update-repository.sh